#ifndef _ADC_H_
#define _ADC_H_

#include <stdint.h>

#include "chip.h"
#include "uart.h"

// PIN CONFIGS
#define ADC_CH2_PIN IOCON_PIO1_1
#define ADC_CH3_PIN IOCON_PIO1_2
#define ADC_CH4_PIN IOCON_PIO1_3
#define ADC_CH5_PIN IOCON_PIO1_4

#define ADC_CH2_PIN_CFG (IOCON_FUNC2 | IOCON_MODE_INACT | IOCON_ADMODE_EN)
#define ADC_CH3_PIN_CFG (IOCON_FUNC2 | IOCON_MODE_INACT | IOCON_ADMODE_EN)
#define ADC_CH4_PIN_CFG (IOCON_FUNC2 | IOCON_MODE_INACT | IOCON_ADMODE_EN)
#define ADC_CH5_PIN_CFG (IOCON_FUNC1 | IOCON_MODE_INACT | IOCON_ADMODE_EN)

// FUNCTIONS
void Init_Internal_ADC(void);

uint16_t Read_Internal_ADC(ADC_CHANNEL_T channel);

#endif
