#ifndef ADC17_H
#define ADC17_H

#include "chip.h"

#define STEERING_CHANNEL ADC_CH0
#define ACCEL_1_CHANNEL ADC_CH2
#define ACCEL_2_CHANNEL ADC_CH3
#define BRAKE_1_CHANNEL ADC_CH4
#define BRAKE_2_CHANNEL ADC_CH5

#define UNUSED_1_CHANNEL ADC_CH1
#define UNUSED_2_CHANNEL ADC_CH6
#define UNUSED_3_CHANNEL ADC_CH7

#define STEERING_PIN IOCON_PIO0_11
#define ACCEL_1_PIN IOCON_PIO1_1
#define ACCEL_2_PIN IOCON_PIO1_2
#define BRAKE_1_PIN IOCON_PIO1_3
#define BRAKE_2_PIN IOCON_PIO1_4

#define ACCEL_1_PIN_CONFIG (IOCON_FUNC2 | IOCON_MODE_INACT | IOCON_ADMODE_EN)
#define ACCEL_2_PIN_CONFIG (IOCON_FUNC2 | IOCON_MODE_INACT | IOCON_ADMODE_EN)
#define BRAKE_1_PIN_CONFIG (IOCON_FUNC2 | IOCON_MODE_INACT | IOCON_ADMODE_EN)
#define BRAKE_2_PIN_CONFIG (IOCON_FUNC1 | IOCON_MODE_INACT | IOCON_ADMODE_EN)
#define STEERING_PIN_CONFIG (IOCON_FUNC2 | IOCON_MODE_INACT | IOCON_ADMODE_EN)

void ADC_Init(void);
uint16_t ADC_Read(ADC_CHANNEL_T channel);
uint16_t transform1(uint32_t accel_1_raw);
uint16_t transform2(uint32_t accel_2_raw);

#endif //ADC17_H
