#ifndef _PINS_H_
#define _PINS_H_

#define PIN_EEPROM_CS           2, 9
#define PIN_GPIO1               1, 1
#define PIN_GPIO2               1, 2
#define PIN_CONTACTOR_WELD_1    1, 4
#define PIN_CONTACTOR_WELD_2    1, 3
#define PIN_LOW_SIDE_DETECT     1, 11
#define PIN_HIGH_SIDE_DETECT    3, 2
#define PIN_TEMP_CHECK          0, 3
#define PIN_BMS_FAULT           3, 0
#define PIN_CHARGER_ENABLE      3, 1
#define PIN_LED1                1, 10
#define PIN_LED2                2, 11
#define PIN_LED3                1, 5

#define PIN_IOCON_EEPROM_CS           IOCON_PIO2_9
#define PIN_IOCON_GPIO1               IOCON_PIO1_1
#define PIN_IOCON_GPIO2               IOCON_PIO1_2
#define PIN_IOCON_CONTACTOR_WELD_1    IOCON_PIO1_4
#define PIN_IOCON_CONTACTOR_WELD_2    IOCON_PIO1_3
#define PIN_IOCON_LOW_SIDE_DETECT     IOCON_PIO1_11
#define PIN_IOCON_HIGH_SIDE_DETECT    IOCON_PIO3_2
#define PIN_IOCON_TEMP_CHECK          IOCON_PIO0_3
#define PIN_IOCON_BMS_FAULT           IOCON_PIO3_0
#define PIN_IOCON_CHARGER_ENABLE      IOCON_PIO3_1
#define PIN_IOCON_LED1                IOCON_PIO1_10
#define PIN_IOCON_LED2                IOCON_PIO2_11
#define PIN_IOCON_LED3                IOCON_PIO1_5

#define IOCON_LED1_FUNC IOCON_FUNC0
#define IOCON_LED2_FUNC IOCON_FUNC0
#define IOCON_LED3_FUNC IOCON_FUNC0


// unused pins
#define PIN_23 0, 7
#define PIN_IOCON_23 IOCON_PIO0_7
#define IOCON_PIN_23_FUNC IOCON_FUNC0
#define PIN_29 0, 10
#define PIN_IOCON_29 IOCON_PIO0_10
#define IOCON_PIN_29_FUNC IOCON_FUNC1
#define PIN_32 0, 11
#define PIN_IOCON_32 IOCON_PIO0_11
#define IOCON_PIN_32_FUNC IOCON_FUNC1
#define PIN_33 1, 0
#define PIN_IOCON_33 IOCON_PIO1_0
#define IOCON_PIN_33_FUNC IOCON_FUNC1
#define PIN_9 1, 8
#define PIN_IOCON_9 IOCON_PIO1_8
#define IOCON_PIN_9_FUNC IOCON_FUNC0
#define PIN_17 1, 9
#define PIN_IOCON_17 IOCON_PIO1_9
#define IOCON_PIN_17_FUNC IOCON_FUNC0
#define PIN_2 2, 0
#define PIN_IOCON_2 IOCON_PIO2_0
#define IOCON_PIN_2_FUNC IOCON_FUNC0
#define PIN_21 2, 5
#define PIN_IOCON_21 IOCON_PIO2_5
#define IOCON_PIN_21_FUNC IOCON_FUNC0
#define PIN_1 2, 6
#define PIN_IOCON_1 IOCON_PIO2_6
#define IOCON_PIN_1_FUNC IOCON_FUNC0
#define PIN_11 2, 7
#define PIN_IOCON_11 IOCON_PIO2_7
#define IOCON_PIN_11_FUNC IOCON_FUNC0
#define PIN_12 2, 8
#define PIN_IOCON_12 IOCON_PIO2_8
#define IOCON_PIN_12_FUNC IOCON_FUNC0
#define PIN_25 2, 10
#define PIN_IOCON_25 IOCON_PIO2_10
#define IOCON_PIN_25_FUNC IOCON_FUNC0
#define PIN_48 3, 3
#define PIN_IOCON_48 IOCON_PIO3_3
#define IOCON_PIN_48_FUNC IOCON_FUNC0


#endif // ifndef _PINS_H_
