// COPIED FROM MY17!! (except for names)
// TODO Needs to be fixed with real pin numbers

#ifndef ADC_H
#define ADC_H

#include "chip.h"

#include "types.h"

#define STEERING_CHANNEL ADC_CH0
#define LEFT_THROTTLE_POT_CHANNEL ADC_CH2
#define RIGHT_THROTTLE_POT_CHANNEL ADC_CH3
#define FRONT_BRAKE_CHANNEL ADC_CH4
#define REAR_BRAKE_CHANNEL ADC_CH5

#define UNUSED_1_CHANNEL ADC_CH1
#define UNUSED_2_CHANNEL ADC_CH6
#define UNUSED_3_CHANNEL ADC_CH7

#define STEERING_PIN IOCON_PIO0_11
#define LEFT_THROTTLE_POT_PIN IOCON_PIO1_1
#define RIGHT_THROTTLE_POT_PIN IOCON_PIO1_2
#define FRONT_BRAKE_PIN IOCON_PIO1_3
#define REAR_BRAKE_PIN IOCON_PIO1_4

#define LEFT_THROTTLE_POT_PIN_CONFIG (IOCON_FUNC2 | IOCON_MODE_INACT | IOCON_ADMODE_EN)
#define RIGHT_THROTTLE_POT_PIN_CONFIG (IOCON_FUNC2 | IOCON_MODE_INACT | IOCON_ADMODE_EN)
#define FRONT_BRAKE_PIN_CONFIG (IOCON_FUNC2 | IOCON_MODE_INACT | IOCON_ADMODE_EN)
#define REAR_BRAKE_PIN_CONFIG (IOCON_FUNC1 | IOCON_MODE_INACT | IOCON_ADMODE_EN)
#define STEERING_PIN_CONFIG (IOCON_FUNC2 | IOCON_MODE_INACT | IOCON_ADMODE_EN)

void ADC_Init(void);
uint16_t ADC_Read(ADC_CHANNEL_T channel);

#endif //ADC_H
